"use client";

import { type FormEvent, useEffect, useRef, useState } from "react";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Gift, Heart, Mail, MapPin, Menu, Plane, Volume2, VolumeX, X } from "lucide-react";

const photos = ["9e855fdb-6a91-46ee-b436-e5d7843d88c6.jpg","b5ea757b-3020-47d7-905b-2ba69562a8f9.jpg","10d73bd7-9b53-4105-9eab-56764f80a1de.jpg","1df7a90f-f30c-41b7-987a-4017fc54a819.jpg","96d910b7-c2a8-4f49-a7df-237eed9b554b.jpg","c0c8859d-f923-47ec-b95f-9ce0fa0e1174.jpg"];

function Countdown(){const [time,setTime]=useState({days:0,hours:0,minutes:0,seconds:0});useEffect(()=>{const update=()=>{const distance=Math.max(0,new Date("2026-10-03T13:00:00+08:00").getTime()-Date.now());setTime({days:Math.floor(distance/86400000),hours:Math.floor((distance/3600000)%24),minutes:Math.floor((distance/60000)%60),seconds:Math.floor((distance/1000)%60)})};update();const timer=window.setInterval(update,1000);return()=>window.clearInterval(timer)},[]);return <div className="countdown" aria-label="Countdown to the wedding">{Object.entries(time).map(([label,value])=><div key={label}><strong>{String(value).padStart(2,"0")}</strong><span>{label}</span></div>)}</div>}

function RSVPSection(){
  const [guest,setGuest]=useState({name:"",email:"",seats:"1",attending:"yes"});
  const [complete,setComplete]=useState(false);
  const bookingCode=(guest.name.replace(/[^a-z0-9]/gi,"").slice(0,4)||"GUEST").toUpperCase()+"-031026";
  const saveBoardingPass=async()=>{const image=new Image();image.src="/images/boarding-pass-design.jpeg";await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error("Boarding pass image could not be loaded"))});const canvas=document.createElement("canvas");canvas.width=1600;canvas.height=700;const context=canvas.getContext("2d");if(!context)return;context.fillStyle="#fffaf4";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,1600,632);context.strokeStyle="#b9471e";context.lineWidth=3;context.beginPath();context.moveTo(0,633);context.lineTo(1600,633);context.stroke();context.fillStyle="#a84220";context.font="700 18px Arial";context.fillText("PASSENGER",55,667);context.fillStyle="#2f1c16";context.font="700 25px Georgia";context.fillText(guest.name.toUpperCase(),205,669);context.textAlign="right";context.fillStyle="#a84220";context.font="700 18px Arial";context.fillText(`BOOKING ${bookingCode}  ·  ${guest.seats} GUEST${guest.seats==="1"?"":"S"}`,1545,668);const link=document.createElement("a");link.download=`${guest.name.trim().replace(/\s+/g,"-").toLowerCase()||"guest"}-boarding-pass.jpg`;link.href=canvas.toDataURL("image/jpeg",.95);link.click()};
  useEffect(()=>{if(!complete)return;const originalPrint=window.print;window.print=()=>{void saveBoardingPass()};return()=>{window.print=originalPrint}},[complete,guest.name,guest.seats,bookingCode]);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setComplete(true);const answer=guest.attending==="yes"?`joyfully accepts for ${guest.seats} guest${guest.seats==="1"?"":"s"}`:"regretfully cannot attend";const subject=encodeURIComponent(`Wedding RSVP — ${guest.name}`);const body=encodeURIComponent(`Dear Dexter and Rosemarie,\n\n${guest.name} ${answer}.\nGuest email: ${guest.email}\n\nWith love,\n${guest.name}`);window.location.href=`mailto:dexpresbitero03@gmail.com?cc=incrose27@gmail.com&subject=${subject}&body=${body}`};
  const saveReminder=()=>{const calendar=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Dexter and Rosemarie//Wedding//EN","BEGIN:VEVENT","UID:dexter-rosemarie-wedding-20261003","DTSTAMP:20260920T000000Z","DTSTART:20261003T050000Z","DTEND:20261003T120000Z","SUMMARY:Dexter & Rosemarie’s Wedding","LOCATION:Iglesia Ni Cristo - Lokal ng Sapalibutad, Magalang, Pampanga","DESCRIPTION:Ceremony at 1:00 PM followed by the reception at Finizzio Grande.","BEGIN:VALARM","TRIGGER:-P1D","ACTION:DISPLAY","DESCRIPTION:Wedding reminder","END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([calendar],{type:"text/calendar"}));const link=document.createElement("a");link.href=url;link.download="dexter-rosemarie-wedding.ics";link.click();URL.revokeObjectURL(url)};
  return <section className="rsvp" id="rsvp"><div className="rsvp-panel"><p className="eyebrow">We hope you can join us</p><h2>Kindly respond</h2><p>Please confirm on or before <strong>September 25, 2026</strong>. Your email app will open with your response ready to send.</p>{!complete?<form className="rsvp-form" onSubmit={submit}><label>Full name<input required value={guest.name} onChange={event=>setGuest({...guest,name:event.target.value})} autoComplete="name" placeholder="Your full name"/></label><label>Email address<input required type="email" value={guest.email} onChange={event=>setGuest({...guest,email:event.target.value})} autoComplete="email" placeholder="you@example.com"/></label><label>Will you attend?<select value={guest.attending} onChange={event=>setGuest({...guest,attending:event.target.value})}><option value="yes">Joyfully accepts</option><option value="no">Regretfully declines</option></select></label>{guest.attending==="yes"&&<label>Confirmed seats<select value={guest.seats} onChange={event=>setGuest({...guest,seats:event.target.value})}>{[1,2,3,4].map(number=><option key={number}>{number}</option>)}</select></label>}<button type="submit"><Mail/>Prepare my RSVP</button></form>:<div className="rsvp-complete"><p className="confirmation-note">Your RSVP is ready in your email app. Send it to complete your response.</p>{guest.attending==="yes"&&<><article className="boarding-pass" aria-label="Personalized wedding boarding pass"><div className="pass-main"><p className="pass-kicker">Boarding pass · Welcome aboard</p><h3>Dexter <i>&amp;</i> Rosemarie</h3><div className="pass-route"><span>DP</span><Plane/><span>RA</span></div><dl><div><dt>Passenger</dt><dd>{guest.name}</dd></div><div><dt>Date</dt><dd>03 Oct 2026</dd></div><div><dt>Boarding</dt><dd>1:00 PM</dd></div><div><dt>Guests</dt><dd>{guest.seats}</dd></div></dl></div><div className="pass-stub"><span>D&amp;R</span><strong>{bookingCode}</strong><small>Magalang · Pampanga</small><div className="barcode" aria-hidden="true"/></div></article><div className="pass-actions"><button type="button" onClick={()=>window.print()}>Save boarding pass</button><button type="button" onClick={saveReminder}><CalendarDays/>Add reminder</button></div></>}<button className="edit-rsvp" type="button" onClick={()=>setComplete(false)}>Edit response</button></div>}</div></section>
}

export default function Home(){
  const [opened,setOpened]=useState(false);const [menuOpen,setMenuOpen]=useState(false);const [musicPlaying,setMusicPlaying]=useState(false);const [carouselIndex,setCarouselIndex]=useState(0);const audioRef=useRef<HTMLAudioElement|null>(null);const progressRef=useRef<HTMLDivElement|null>(null);const touchStartRef=useRef(0);
  const getAudio=()=>{if(!audioRef.current){audioRef.current=new Audio("/audio/tahanan-el-manu.mp3");audioRef.current.loop=true;audioRef.current.volume=.42}return audioRef.current};
  const openInvitation=()=>{const audio=getAudio();audio.play().then(()=>setMusicPlaying(true)).catch(()=>setMusicPlaying(false));setOpened(true);window.setTimeout(()=>window.scrollTo(0,0),0)};
  const toggleMusic=()=>{const audio=getAudio();if(audio.paused){audio.play().then(()=>setMusicPlaying(true)).catch(()=>setMusicPlaying(false))}else{audio.pause();setMusicPlaying(false)}};
  const changeSlide=(direction:number)=>setCarouselIndex(current=>(current+direction+photos.length)%photos.length);
  useEffect(()=>{if(!opened||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const items=[...document.querySelectorAll<HTMLElement>(".section, .date-band, .attire, .rsvp, footer")];items.forEach(item=>item.classList.add("motion-reveal"));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("motion-visible");observer.unobserve(entry.target)}}),{threshold:.1,rootMargin:"0px 0px -8% 0px"});items.forEach(item=>observer.observe(item));return()=>observer.disconnect()},[opened]);
  useEffect(()=>{if(!opened)return;let frame=0;const update=()=>{frame=0;const y=window.scrollY;const max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight);if(progressRef.current)progressRef.current.style.transform=`scaleX(${Math.min(1,y/max)})`;document.querySelector(".nav-shell")?.classList.toggle("nav-scrolled",y>40);const hero=document.querySelector<HTMLElement>(".hero>img");if(hero&&!window.matchMedia("(prefers-reduced-motion: reduce)").matches)hero.style.setProperty("--parallax",`${Math.min(y*.09,55)}px`)};const onScroll=()=>{if(!frame)frame=window.requestAnimationFrame(update)};update();window.addEventListener("scroll",onScroll,{passive:true});return()=>{window.removeEventListener("scroll",onScroll);if(frame)window.cancelAnimationFrame(frame)}},[opened]);
  useEffect(()=>{if(!opened||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>changeSlide(1),5500);return()=>window.clearInterval(timer)},[opened]);
  if(!opened)return <main className="landing"><p className="landing-message"><span>Here’s your passport</span> to our journey</p><button className="passport-cover" onClick={openInvitation} aria-label="Open wedding invitation"><span className="cover-title">Passport</span><span className="cover-subtitle">Wedding invitation</span><span className="cover-emblem">D<i>&amp;</i>R</span><span className="cover-names">Dexter Presbitero<br/>Rosemarie Acala</span><span className="cover-open">Tap to open <Plane/></span></button></main>;

  return <main className="invitation">
    <style>{`.carousel-slide{min-width:100%;overflow:hidden;display:flex;align-items:center;justify-content:center}.carousel-slide img{width:auto!important;height:auto!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;object-position:center!important}`}</style>
    <div className="scroll-progress" ref={progressRef} aria-hidden="true"/>
    <nav className="nav-shell" aria-label="Main navigation"><a className="monogram" href="#home">D<span>&amp;</span>R</a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button><div className={menuOpen?"nav-links open":"nav-links"}><a href="#story" onClick={()=>setMenuOpen(false)}>Our story</a><a href="#details" onClick={()=>setMenuOpen(false)}>The day</a><a href="#attire" onClick={()=>setMenuOpen(false)}>Attire</a><a href="#entourage" onClick={()=>setMenuOpen(false)}>Entourage</a><a href="#gallery" onClick={()=>setMenuOpen(false)}>Gallery</a><a className="nav-rsvp" href="#rsvp" onClick={()=>setMenuOpen(false)}>RSVP</a></div></nav>
    <button className="music-control" onClick={toggleMusic} aria-label={musicPlaying?"Pause background music":"Play background music"}>{musicPlaying?<Volume2/>:<VolumeX/>}<span>{musicPlaying?"Music on":"Music off"}</span></button>
    <section className="hero" id="home"><img src="/images/9e855fdb-6a91-46ee-b436-e5d7843d88c6.jpg" alt="Dexter and Rosemarie"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">We are getting married</p><h1><span>Dexter</span><i>&amp;</i><span>Rosemarie</span></h1><p className="hero-date">03 · 10 · 2026&nbsp;&nbsp; — &nbsp;&nbsp;Magalang, Pampanga</p></div><a className="scroll-cue" href="#story"><span>Our invitation</span><ChevronDown/></a></section>
    <section className="intro section" id="story"><p className="eyebrow rust">Together with our families</p><h2>We joyfully invite you<br/>to celebrate our love.</h2><p className="intro-copy">As we begin a new chapter together, your presence would make our day even more meaningful.</p><div className="parents"><div><span>Parents of the groom</span><p>Wilson Pangilinan<br/>Myrna Presbitero</p></div><Heart/><div><span>Parents of the bride</span><p>Ronelo Acala<br/>Gemma Acala</p></div></div></section>
    <section className="date-band"><div><p>Save the date</p><h2>October 3, 2026</h2><span>Saturday · One o’clock in the afternoon</span></div><Countdown/></section>
    <section className="details section" id="details"><div className="section-heading"><p className="eyebrow rust">The wedding day</p><h2>Where &amp; when</h2></div><div className="detail-grid"><article><div className="detail-icon"><CalendarDays/></div><p className="detail-number">01</p><h3>Ceremony</h3><p>Iglesia Ni Cristo<br/>Lokal ng Sapalibutad</p><strong><Clock3/>1:00 PM</strong><a href="https://maps.google.com/?q=Iglesia+Ni+Cristo+Lokal+ng+Sapalibutad" target="_blank" rel="noreferrer"><MapPin/>View location</a></article><article><div className="detail-icon"><Heart/></div><p className="detail-number">02</p><h3>Reception</h3><p>Finizzio Grande<br/>Bornal St., Sta. Cruz, Magalang</p><strong><Clock3/>4:00 PM</strong><a href="https://maps.google.com/?q=Finizzio+Grande+Magalang+Pampanga" target="_blank" rel="noreferrer"><MapPin/>View location</a></article></div></section>
    <section className="attire" id="attire"><div className="attire-image"><img src="/images/3a7257fc-fe4c-4e91-afb9-f70a3222d557.jpg" alt="Wedding attire inspiration"/></div><div className="attire-copy"><p className="eyebrow">Dress code</p><h2>Autumn formal</h2><p>We kindly encourage our guests to wear formal attire in warm, earthy wedding colors.</p><div className="swatches">{["#4b1d0b","#74330f","#994822","#bd5d2a","#d67a35","#dda165","#e8bd8b"].map(color=><span key={color} style={{background:color}}/>)}</div><small>Please reserve white for the bride.</small></div></section>
    <section className="entourage section" id="entourage"><div className="entourage-copy"><p className="eyebrow rust">Standing beside us</p><h2>Our entourage</h2><p>With grateful hearts, we honor the family and friends who will stand with us as witnesses and companions on our wedding day.</p></div><figure className="entourage-card"><img src="/images/entourage.jpeg" alt="Wedding entourage and sponsors of Dexter and Rosemarie" loading="lazy"/></figure></section>
    <section className="gallery section" id="gallery"><div className="section-heading"><p className="eyebrow rust">A little glimpse of us</p><h2>Our favorite moments</h2></div><div className="carousel" onTouchStart={event=>{touchStartRef.current=event.touches[0].clientX}} onTouchEnd={event=>{const distance=event.changedTouches[0].clientX-touchStartRef.current;if(Math.abs(distance)>45)changeSlide(distance>0?-1:1)}}><div className="carousel-track" style={{transform:`translateX(-${carouselIndex*100}%)`}}>{photos.map((photo,index)=><figure className="carousel-slide" key={photo} aria-hidden={carouselIndex!==index}><img src={`/images/${photo}`} alt={`Dexter and Rosemarie, photo ${index+1}`} loading={index<2?"eager":"lazy"}/></figure>)}</div><button className="carousel-arrow previous" onClick={()=>changeSlide(-1)} aria-label="Previous image"><ChevronLeft/></button><button className="carousel-arrow next" onClick={()=>changeSlide(1)} aria-label="Next image"><ChevronRight/></button></div><div className="carousel-dots" aria-label="Choose gallery image">{photos.map((_,index)=><button key={index} className={carouselIndex===index?"active":""} onClick={()=>setCarouselIndex(index)} aria-label={`Show image ${index+1}`} aria-current={carouselIndex===index?"true":undefined}/>)}</div><p className="carousel-count">{String(carouselIndex+1).padStart(2,"0")} <span>/ {String(photos.length).padStart(2,"0")}</span></p></section>
    <section className="gift-guide section" id="gifts"><div className="gift-icon"><Gift/></div><p className="eyebrow rust">With love and gratitude</p><h2>Gift guide</h2><p>Your presence is the greatest gift we could receive on our special day. If you wish to give, a monetary gift or a thoughtful gift of your choice would be warmly appreciated.</p></section>
    <RSVPSection/>
    <footer><button className="footer-mark" onClick={()=>{setOpened(false);window.scrollTo(0,0)}}>D<span>&amp;</span>R</button><p>October 3, 2026 · Magalang, Pampanga</p><span>Made with love</span></footer>
  </main>
}
